post_install() {
    do_install ${1}
}

post_upgrade() {
    do_install ${1}
}

# -----------------------------------------------------------------------------------

do_install() {
    cat << EOF

==> i915-patched install/upgrade note:
--------------------------------------------------------------------------------
Linux kernel >= 5.0 i915 module patched to fix Dell XPS 9570 black screen issue
--------------------------------------------------------------------------------

EOF
}
